// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACnBo_NRng82t1xANFzPYL5gyotR7PQZI',
    appId: '1:780766243544:web:ae83bc33c1b75641ea85ad',
    messagingSenderId: '780766243544',
    projectId: 'bookstore-c54ae',
    authDomain: 'bookstore-c54ae.firebaseapp.com',
    databaseURL: 'https://bookstore-c54ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookstore-c54ae.appspot.com',
    measurementId: 'G-KRGXRM4E9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE7GovrNH7n-tFidIewd0S5XLhNubG7Xs',
    appId: '1:780766243544:android:8ea17fd43e4270c3ea85ad',
    messagingSenderId: '780766243544',
    projectId: 'bookstore-c54ae',
    databaseURL: 'https://bookstore-c54ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bookstore-c54ae.appspot.com',
  );
}
